# Generated by Django 4.2.3 on 2023-08-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUploadModel',
        ),
    ]
